### ISSUE TITLE
Cannot update owner, POC, metadata author fields in layers

### ISSUE THREAD

**Issue by ErikKBethke** [GFDRR/geonode#33] opened 2017-04-27 17:08 UTC
Search functionality for layers does not function properly, cannot update these three fields for any layers.

**Comment by fvanderbiest** [comment] 2017-06-02 14:46
Can you try again on production server ?

**Comment by ErikKBethke** [comment] 2017-06-02 23:57
Search functionality still not populating.

Tested on:
http://www.geonode-gfdrrlab.org/layers/hazard:hurriwind_mex_50tr/metadata
http://www.geonode-gfdrrlab.org/layers/hazard:hurriwind_mex_100tr/metadata

Let me know if there are other layers or servers you'd like me to attempt.

**Comment by ErikKBethke** [comment] 2017-06-28 16:39
@fvanderbiest following up, do we have any progress on the ability to do searches for owner/POC/etc.?

Thank you!

**Comment by fvanderbiest** [comment] 2017-08-04 08:53
I could reproduce, indeed there's no autocomplete on these fields, eg
![capture du 2017-08-04 10-52-56](https://user-images.githubusercontent.com/265319/28961588-23967df4-7903-11e7-8d06-09573f6b6496.png)

No JS error, no XHR triggered ... will look into it.

**Comment by stufraser1** [comment] 2017-08-10 12:11
Also applicable in admin side, for example on entering text into auto box 'Keywords region:' at https://www.geonode-gfdrrlab.org/admin/documents/document/1334/

**Comment by fvanderbiest** [comment] 2017-08-29 08:56
On int, we're now up to date with geonode 2.6.2 that was released last week.
I'll test with a fresh install to check where the issue comes from.

**Comment by fvanderbiest** [comment] 2017-08-29 12:09
With https://github.com/fvanderbiest/ansible_vagrant_geonode I bootstrapped a fresh 2.6.2 Geonode in a clean environment.
The behavior is the same. 

I'll try with geonode master to check if there's a fix upstream.

**Comment by fvanderbiest** [comment] 2017-08-29 13:12
> I'll try with geonode master to check if there's a fix upstream.

The setup failed for some reason.

I'm asking the community with https://github.com/GeoNode/geonode/issues/3245

**Comment by Vampouille** [comment] 2017-09-15 07:42
I re-apply our docker setup on 2.7.x branch and it fix POC and metadata author fields update. Autocompletion on those fields are also working.

![capture du 2017-09-15 09-41-39](https://user-images.githubusercontent.com/7067560/30471742-2560fe6c-99fa-11e7-9f3c-13aff1f7ba4d.png)

**Comment by ErikKBethke** [comment] 2017-09-27 14:46
Great to see re-applying the docker seems to fix the issue @Vampouille. Any idea when this could get pushed live?

**Comment by Vampouille** [comment] 2017-09-28 16:26
I just finish installation on int env. ... but I had to make several manual operation : 

image change : camptocamp/geonode_django:20170831131436 --> camptocamp/geonode_django:2.7-gfdrr-7ea0951

```
$ python manage.py migrate

column base_resourcebase.alternate does not existLINE 1: ...id" AS Col4, "base_resourcebase"."title" AS Col5, "base_reso...                                                             ^
```
celery tables were empty so I drop it and let django recreate those tables :

```sql
DROP TABLE celery_taskmeta CASCADE;
DROP TABLE celery_tasksetmeta CASCADE;
DROP TABLE djcelery_crontabschedule CASCADE;
DROP TABLE djcelery_intervalschedule CASCADE;
DROP TABLE djcelery_periodictask CASCADE;
DROP TABLE djcelery_periodictasks CASCADE;
DROP TABLE djcelery_taskstate CASCADE;
DROP TABLE djcelery_workerstate CASCADE;
```
```
$ python manage.py migrate

column base_region.bbox_x0 does not existLINE 1: ...ase_region"."name_en", "base_region"."parent_id", "base_regi...                                                             ^
```

bbox_x0 is not present in migrations files. So I drop table and restore it from a fresh database from docker composition with: 

On local workstation:
```
$ pg_dump -h 127.0.0.1 -p 54322 --username geonode --format=directory --file=base_region --no-owner --verbose --no-privileges --table=base_region geonode
```
On server:
```sql
ALTER TABLE public.base_resourcebase_regions DROP CONSTRAINT base_resourcebase_regions_region_id_fkey;
DROP TABLE base_region;
```

```
$ pg_restore -v -h lb.postgres-cluster --dbname=geonode --username geonode base_region
```

```sql
ALTER TABLE public.base_resourcebase_regions
  ADD CONSTRAINT base_resourcebase_regions_region_id_fkey FOREIGN KEY (region_id)
      REFERENCES public.base_region (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
```

**Comment by Vampouille** [comment] 2017-10-03 11:47
Geonode 2.7 fix auto-completion on author, owner and point of contact fileds. But modification on those fields are not saved in database. I will investigate on difference between local run of docker composition and installation on int env.

**Comment by stufraser1** [comment] 2017-10-12 14:08
@Vampouille @vdeparday @ErikKBethke  We need a resolution to this, so we can publicise geonode and TH! more widely - at present, data owner in TH is not shown accurately, due to this issue, and we should be able to correct the data owner.

**Comment by Vampouille** [comment] 2017-10-16 12:43
I just switch prod instance on geonode 2.7: 
camptocamp/geonode_django:20170802161031 --> camptocamp/geonode_django:2.7-gfdrr-7ea0951

I need to delete celery tables with : 
```sql
DROP TABLE celery_taskmeta CASCADE;
DROP TABLE celery_tasksetmeta CASCADE;
DROP TABLE djcelery_crontabschedule CASCADE;
DROP TABLE djcelery_intervalschedule CASCADE;
DROP TABLE djcelery_periodictask CASCADE;
DROP TABLE djcelery_periodictasks CASCADE;
DROP TABLE djcelery_taskstate CASCADE;
DROP TABLE djcelery_workerstate CASCADE;
```

**Comment by stufraser1** [comment] 2017-10-24 08:26
Hi @Vampouille 
@ErikKBethke notes the owner/author fields are still not populating. I understand from the above you're still working on this? Do you have an idea of when it might be resolved? i.e. will it be on the next version of geonode or fixable in this version? Thanks

**Comment by Vampouille** [comment] 2018-06-06 08:08
I tested edition of Owner, POC and Metadata Author on fresh install of 2.7.x branch with this composition : https://github.com/olivierdalang/SPCgeonode.
Edition is working :-)

We need to test again after applying GFDRR patches (database model, layout, ...)

**Comment by fjacon** [comment] 2018-10-09 10:01
@stufraser1 geonode 2.8 is deployed on integration server
https://int.geonode-gfdrrlab.org/
this issue is solved. Can you check ?

**Comment by stufraser1** [comment] 2018-10-09 14:33
Tested: POC, owner, metadata author updates using text entry box. New POC etc successfully saved to layer file, closing.

**Comment by stufraser1** [comment] 2018-11-14 11:19
Attempting to update layer owner, point of contact and author fields on production server today does not work. I can enter text in the field, but when I press 'update', it returns to the layer pages with no change to those fields. 

I have attempted to change owner, etc,  to Fathom via front end and in django administration on layer:
https://www.geonode-gfdrrlab.org/layers/hazard:adm2_uu_v5_4bit


Also failed on trying to change owner etc to gfdrr on:
https://www.geonode-gfdrrlab.org/layers/hazard:wgs_hazard_viet500_1km

**Comment by pvalsecc** [comment] 2018-11-30 09:32
Bug in geonode, fixed there: https://github.com/GeoNode/geonode/commit/1946d516a9a855931dc64b79748a70a12f363cba
I'm backporting the fix

**Comment by pvalsecc** [comment] 2018-11-30 09:44
Fix tested on int and deployed on prod.

**Closed as completed by pvalsecc** 2018-11-30 09:44 UTC
Labels: 1-blocking, fixed-on-2.8, fixed-on-int-server-2.8
